# Compiles platform/shaders to SPIR-V (Vulkan) and, through SPIRV-Cross, to MSL
# (Metal), and writes both as byte arrays. The generated header is committed, so
# normal builds need neither tool.
#   cmake [-DGLSLANG=glslangValidator] [-DSPIRV_CROSS=spirv-cross] [-DOUTPUT=file.h]
#         -P scripts/compile_gpu_shaders.cmake
# The build also exposes this as the `doom-gpu-shaders` target.
cmake_minimum_required(VERSION 3.21)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT GLSLANG)
    find_program(GLSLANG glslangValidator REQUIRED)
endif()
if(NOT SPIRV_CROSS)
    find_program(SPIRV_CROSS spirv-cross REQUIRED)
endif()
if(NOT OUTPUT)
    set(OUTPUT "${root}/platform/gpu_shaders.h")
endif()
if(NOT WORK)
    set(WORK "${CMAKE_CURRENT_BINARY_DIR}/gpu-shaders")
endif()
file(MAKE_DIRECTORY "${WORK}")
# name|source|defines (comma separated)
set(shaders
    "world_vert|world.vert|"
    "reflect_vert|world.vert|REFLECT"
    "screen_vert|screen.vert|"
    "sky_vert|screen.vert|SKY"
    "world_frag|world.frag|"
    "opaque_frag|world.frag|OPAQUE"
    "cutout_frag|world.frag|CUTOUT"
    "coverage_frag|world.frag|COVERAGE"
    "sky_frag|sky.frag|"
    "sky_surface_frag|sky.frag|SURFACE"
    "shadow_frag|shadow.frag|"
    "decal_frag|shadow.frag|DECAL"
    "particle_frag|flat.frag|"
    "solid_frag|flat.frag|SOLID"
    "heat_frag|flat.frag|HEAT"
    "hud_frag|hud.frag|"
    "emission_frag|emission.frag|"
    "blur_frag|blur.frag|"
    "mist_frag|mist.frag|"
    "present_frag|present.frag|"
    "depth_frag|depth.frag|")
set(header "/* Generated by scripts/compile_gpu_shaders.cmake from platform/shaders; do not edit. */\n")
string(APPEND header "#ifndef DOOM_GPU_SHADERS_H\n#define DOOM_GPU_SHADERS_H\n")
foreach(entry IN LISTS shaders)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 name)
    list(GET parts 1 source)
    list(LENGTH parts count)
    set(defines)
    if(count GREATER 2)
        list(GET parts 2 list)
        string(REPLACE "," ";" list "${list}")
        foreach(define IN LISTS list)
            list(APPEND defines "-D${define}")
        endforeach()
    endif()
    # METAL renumbers storage buffers for SDL_gpu's Metal layout; MSL uses
    # the SPIR-V binding numbers directly as buffer/texture/sampler indices.
    foreach(variant spv metal)
        set(variant_defines ${defines})
        if(variant STREQUAL "metal")
            list(APPEND variant_defines -DMETAL)
        endif()
        execute_process(COMMAND "${GLSLANG}" -V --target-env vulkan1.0 --quiet ${variant_defines}
                -o "${WORK}/${name}.${variant}.spv" "${root}/platform/shaders/${source}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE output)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Shader ${name} (${source}) failed:\n${output}")
        endif()
    endforeach()
    execute_process(COMMAND "${SPIRV_CROSS}" --msl --msl-version 20100 --msl-decoration-binding
            --output "${WORK}/${name}.metal" "${WORK}/${name}.metal.spv"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE output)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "MSL translation of ${name} failed:\n${output}")
    endif()
    foreach(pair "spv|${name}.spv.spv" "msl|${name}.metal")
        string(REPLACE "|" ";" pair "${pair}")
        list(GET pair 0 prefix)
        list(GET pair 1 file)
        file(READ "${WORK}/${file}" bytes HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${bytes}")
        string(REGEX REPLACE "((0x..,){24})" "\\1\n" bytes "${bytes}")
        string(APPEND header "static const unsigned char doom_${prefix}_${name}[]={\n${bytes}};\n")
    endforeach()
endforeach()
string(APPEND header "#endif\n")
file(WRITE "${OUTPUT}" "${header}")
message(STATUS "Wrote ${OUTPUT}")
